# the defaults in this file reflect original postgres defaults
# found in postgres.conf


# general defaults
port: 5432

# replication related
# all are ignored when streaming_replication is 'off'
streaming_replication: 'off' # or 'on'
streaming_master_ip: 'localhost' # or hostvars[groups['masters'][0]]['ansible_eth0']['ipv4']['address']
archive_command: 'cd .'
sr_mode: 'master' # or 'slave'
replicator_user: 'replicator'
replicator_pass: 'replication'
